%X:\programs\mfiles\contrib as of 8/24/1998 at 12:32:29
%ARROW3.M   % function arrow3( V , X0 , R , L , Scale , N )                               
%WORM3.M   %function [X,Y,Z]=worm3(Xc,Yc,Zc,R,N)                                     
%EZLEGEND.M   %                                                                             
%suptitle.m   %SUPTITLE Puts a title above all subplots.                                       
%bmpread.m   %BMPREAD Read a BMP (Microsoft Windows Bitmap) file from disk.    
%pcxread.m   %PCXREAD Read a PCX (ZSoft Paint Format) file from disk.            
%tiffread.m   %TIFFREAD Read a TIFF (Tagged Image File Format) file from disk.           
%hdrload.m                                                                        
%loadbmp.m   % LOADBMP  Load Microsoft Windows 3.x .BMP format image files.              
%savebmp.m   % SAVEBMP  Save Microsoft Windows 3.x .BMP format image files.              
%mycursor.m   % MYCURSOR places a user-defined cursor in the current axes.       
%rotmat.m   % ROTMAT calculates a fundamental rotation matrix                           
%xform.m   % XFORM transforms the vector x using n rotation matrices       
%wavrea.m   %WAVREA  Load Microsoft Windows 3.1 .WAV format sound files.                
%mu2lin.m   %MU2LIN	Mu-law to linear conversion.                              
%wavwri.m   %WAVWRI Saves Microsoft Windows 3.1 .WAV format sound files.                   
%dec2hex.m   %DEC2HEX DEC2HEX(d) returns the hex number corresponding to the decimal
%hex2dec.m   %HEX2DEC  HEX2DEC('X') returns the decimal number corresponding to the
