% ************** MATLAB "M" file  (jim Patton) *************
% The following sets up for starting the batch processing in the middle
% it will spawn regmas8b.
% initiatied Friday, June 16, 1995 by jim patton from 'reg_mastr.m'
%~~~~~~~~~~~~~~~~~~~~~~ Begin Program: ~~~~~~~~~~~~~~~~~~~~~~~~~~

fprintf('\n*** resume.m (jim patton) ***\n');

%__________________________________________________
ROOTNAME='regA_'
cd \jim\lee\energy\regressi\devel
setpath
load c:\jim\lee\energy\regressi\base_dir
load c:\jim\lee\energy\regressi\best
eval(['cd ' base_dir]);  cd;
resume_switch 	= 1;
ROOTNAME 	= 'regA_';
SAVEDIR 	='c:\jim\lee\energy\regressi\';
engin;
