%______*** MATLAB "M" function (jim Patton) ***_______
%
% The following sizes & places the figure windows 
% INITIATED:	4 AUG 1994
%______________________________________________________

figure(1); clg; set(1,'Position', [950 760 300 200]);
figure(2); clg; set(2,'Position', [950 500 300 200]);
figure(3); clg; set(3,'Position', [950 250 300 200]);
figure(4); clg; set(4,'Position', [950 70 300 150]);

%figure(1); clg; set(1,'Position', [10 400 300 200]);
%figure(2); clg; set(2,'Position', [340 400 300 200]);
%figure(3); clg; set(3,'Position', [340 40 300 200]);
%figure(4); clg; set(4,'Position', [300 40 300 200]);


