% **********.M MATLAB "M" file (Patton) *********
%  SYNTAX:	
%  INPUTS:   	
%		
%		
%		
%		
%  OUTPUTS:	
%		
%  CALLS:	
%		
%		
%  VERSIONS:	
% 		
% 		
%		
%		
%		
%~~~~~~~~~~~~~~~~~~~~~~~~~~~ Begin: ~~~~~~~~~~~~~~~~~~~~~~~~~~

function ()
fprintf('\n ~.m M-Function ~ '); pause(.01);  % pause updates display now



fprintf('\n END ~.m M-Function ~ '); pause(.01);  % pause updates display now

